
export type ListingsType = {
  id: number,
  name: string,
  permalink: string,
  price: string,
  thumbnail_url: string,
  creator_name: string,
  creator_profile_url: string,
  ratings_count: number,
  ratings_average: string,
  currency_code: string,
  is_pay_what_you_want: boolean,
  category_id: number,
  formatted_price: string
}
const listings = [
  {
    "id": 1,
    "name": "Small Rubber Watch",
    "permalink": "inspiration_freckle",
    "price": "36.67",
    "thumbnail_url": "https://public-files.gumroad.com/ba6pmzf1c8hgtfbicpnpqq7siyb6",
    "creator_name": "Pres. Merrill Schulist",
    "creator_profile_url": "http://vonrueden.test/lorenzo",
    "ratings_count": 55,
    "ratings_average": "4.7",
    "currency_code": "CAD",
    "is_pay_what_you_want": true,
    "category_id": 10,
    "formatted_price": "CAD 36.67"
  },
  {
    "id": 2,
    "name": "Small Rubber Watch",
    "permalink": "inspiration_freckle",
    "price": "36.67",
    "thumbnail_url": "https://public-files.gumroad.com/ba6pmzf1c8hgtfbicpnpqq7siyb6",
    "creator_name": "Pres. Merrill Schulist",
    "creator_profile_url": "http://vonrueden.test/lorenzo",
    "ratings_count": 55,
    "ratings_average": "4.7",
    "currency_code": "CAD",
    "is_pay_what_you_want": true,
    "category_id": 10,
    "formatted_price": "CAD 36.67"
  },
  {
    "id": 3,
    "name": "Small Rubber Watch",
    "permalink": "inspiration_freckle",
    "price": "36.67",
    "thumbnail_url": "https://public-files.gumroad.com/ba6pmzf1c8hgtfbicpnpqq7siyb6",
    "creator_name": "Pres. Merrill Schulist",
    "creator_profile_url": "http://vonrueden.test/lorenzo",
    "ratings_count": 55,
    "ratings_average": "4.7",
    "currency_code": "CAD",
    "is_pay_what_you_want": true,
    "category_id": 10,
    "formatted_price": "CAD 36.67"
  },
  {
    "id": 4,
    "name": "Small Rubber Watch",
    "permalink": "inspiration_freckle",
    "price": "36.67",
    "thumbnail_url": "https://public-files.gumroad.com/ba6pmzf1c8hgtfbicpnpqq7siyb6",
    "creator_name": "Pres. Merrill Schulist",
    "creator_profile_url": "http://vonrueden.test/lorenzo",
    "ratings_count": 55,
    "ratings_average": "4.7",
    "currency_code": "CAD",
    "is_pay_what_you_want": true,
    "category_id": 10,
    "formatted_price": "CAD 36.67"
  },
  {
    "id": 5,
    "name": "Small Rubber Watch",
    "permalink": "inspiration_freckle",
    "price": "36.67",
    "thumbnail_url": "https://public-files.gumroad.com/ba6pmzf1c8hgtfbicpnpqq7siyb6",
    "creator_name": "Pres. Merrill Schulist",
    "creator_profile_url": "http://vonrueden.test/lorenzo",
    "ratings_count": 55,
    "ratings_average": "4.7",
    "currency_code": "CAD",
    "is_pay_what_you_want": true,
    "category_id": 10,
    "formatted_price": "CAD 36.67"
  },
  {
    "id": 6,
    "name": "Small Rubber Watch",
    "permalink": "inspiration_freckle",
    "price": "36.67",
    "thumbnail_url": "https://public-files.gumroad.com/ba6pmzf1c8hgtfbicpnpqq7siyb6",
    "creator_name": "Pres. Merrill Schulist",
    "creator_profile_url": "http://vonrueden.test/lorenzo",
    "ratings_count": 55,
    "ratings_average": "4.7",
    "currency_code": "CAD",
    "is_pay_what_you_want": true,
    "category_id": 10,
    "formatted_price": "CAD 36.67"
  },
  {
    "id": 7,
    "name": "Small Rubber Watch",
    "permalink": "inspiration_freckle",
    "price": "36.67",
    "thumbnail_url": "https://public-files.gumroad.com/ba6pmzf1c8hgtfbicpnpqq7siyb6",
    "creator_name": "Pres. Merrill Schulist",
    "creator_profile_url": "http://vonrueden.test/lorenzo",
    "ratings_count": 55,
    "ratings_average": "4.7",
    "currency_code": "CAD",
    "is_pay_what_you_want": true,
    "category_id": 10,
    "formatted_price": "CAD 36.67"
  },
  {
    "id": 8,
    "name": "Small Rubber Watch",
    "permalink": "inspiration_freckle",
    "price": "36.67",
    "thumbnail_url": "https://public-files.gumroad.com/ba6pmzf1c8hgtfbicpnpqq7siyb6",
    "creator_name": "Pres. Merrill Schulist",
    "creator_profile_url": "http://vonrueden.test/lorenzo",
    "ratings_count": 55,
    "ratings_average": "4.7",
    "currency_code": "CAD",
    "is_pay_what_you_want": true,
    "category_id": 10,
    "formatted_price": "CAD 36.67"
  },
  {
    "id": 9,
    "name": "Small Rubber Watch",
    "permalink": "inspiration_freckle",
    "price": "36.67",
    "thumbnail_url": "https://public-files.gumroad.com/ba6pmzf1c8hgtfbicpnpqq7siyb6",
    "creator_name": "Pres. Merrill Schulist",
    "creator_profile_url": "http://vonrueden.test/lorenzo",
    "ratings_count": 55,
    "ratings_average": "4.7",
    "currency_code": "CAD",
    "is_pay_what_you_want": true,
    "category_id": 10,
    "formatted_price": "CAD 36.67"
  },
];

export default listings